### Import Libraries

In [11]:
import numpy as np
import pandas as pd

### Loading Dataset

In [12]:
df = pd.read_excel("C:/Users/LENOVO/Desktop/data-analytics/Customer Churn/dataset/Churn_Unclean_Project.xlsx")

In [13]:
df.head()

,Customer_ID,Customer_Name,Gender,Age,State,City,Tenure_Months,Subscription_Type,Monthly_Charges,Total_Charges,Contract_Type,Payment_Method,Internet_Service,Tech_Support,Senior_Citizen,Dependents,Churn,Last_Interaction_Date
0,C1000,Abhishek Jaiswal,Female,35.0,Maharashtra,Pune,58.0,basic,1614.26,93273.08,One Year,UPI,Fiber,Yes,No,Yes,No,12-10-2025
1,C1001,Rohit Kumar,Male,NaN,Delhi,Noida,36.0,Premium,429.60,15858.60,Two Year,Cash,DSL,Yes,Yes,No,No,05-03-2026
2,C1002,Pooja Singh,Female,42.0,UP,Kanpur,13.0,Basic,555.03,6869.39,Month-to-Month,Debit Card,5G,No,No,No,Yes,20-02-2026
3,C1003,NaN,Male,59.0,Karnataka,Bengaluru,55.0,Standard,NaN,101349.10,Two Year,UPI,5G,No,No,Yes,No,07-06-2026
4,C1004,Mohit Arora,male,26.0,Gujarat,Ahmedabad,6.0,Premium,314.02,1926.12,One Year,Debit Card,Cable,Yes,No,No,No,02-04-2026

In [14]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 542 entries, 0 to 541
Data columns (total 18 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Customer_ID            542 non-null    str
 1   Customer_Name          533 non-null    str
 2   Gender                 536 non-null    str
 3   Age                    536 non-null    float64
 4   State                  531 non-null    str
 5   City                   539 non-null    str
 6   Tenure_Months          534 non-null    float64
 7   Subscription_Type      530 non-null    str
 8   Monthly_Charges        529 non-null    float64
 9   Total_Charges          533 non-null    float64
 10  Contract_Type          538 non-null    str
 11  Payment_Method         526 non-null    str
 12  Internet_Service       535 non-null    str
 13  Tech_Support           530 non-null    str
 14  Senior_Citizen         534 non-null    str
 15  Dependents             539 non-null    str
 16  Churn                  538 non-null    str
 17  Last_Interaction_Date  539 non-null    str
dtypes: float64(4), str(14)
memory usage: 120.0 KB

In [15]:
df.describe()

              Age  Tenure_Months  Monthly_Charges  Total_Charges
count  536.000000     534.000000       529.000000     533.000000
mean    44.399254      36.406367      1335.269206   49745.287336
std     18.556837      20.669599       715.972838   41644.111657
min      3.000000       1.000000     -2454.770000  -99781.820000
25%     30.000000      19.000000       756.570000   18770.290000
50%     44.000000      38.000000      1306.800000   40649.600000
75%     57.000000      54.000000      1900.650000   75647.400000
max    165.000000      72.000000      2492.510000  171429.830000

In [16]:
df.shape

(542, 18)

### Check Missing Values

In [17]:
df.isnull().sum()

Customer_ID               0
Customer_Name             9
Gender                    6
Age                       6
State                    11
City                      3
Tenure_Months             8
Subscription_Type        12
Monthly_Charges          13
Total_Charges             9
Contract_Type             4
Payment_Method           16
Internet_Service          7
Tech_Support             12
Senior_Citizen            8
Dependents                3
Churn                     4
Last_Interaction_Date     3
dtype: int64

### Duplicated Values

In [18]:
df.duplicated().sum()

np.int64(7)

In [19]:
df.drop_duplicates(inplace=True)

### Replace Dirty values

In [20]:
df.replace(["N/A","NULL",""," "],np.nan,inplace=True)

,Customer_ID,Customer_Name,Gender,Age,State,City,Tenure_Months,Subscription_Type,Monthly_Charges,Total_Charges,Contract_Type,Payment_Method,Internet_Service,Tech_Support,Senior_Citizen,Dependents,Churn,Last_Interaction_Date
0,C1000,Abhishek Jaiswal,Female,35.0,Maharashtra,Pune,58.0,basic,1614.26,93273.08,One Year,UPI,Fiber,Yes,No,Yes,No,12-10-2025
1,C1001,Rohit Kumar,Male,NaN,Delhi,Noida,36.0,Premium,429.60,15858.60,Two Year,Cash,DSL,Yes,Yes,No,No,05-03-2026
2,C1002,Pooja Singh,Female,42.0,UP,Kanpur,13.0,Basic,555.03,6869.39,Month-to-Month,Debit Card,5G,No,No,No,Yes,20-02-2026
3,C1003,NaN,Male,59.0,Karnataka,Bengaluru,55.0,Standard,NaN,101349.10,Two Year,UPI,5G,No,No,Yes,No,07-06-2026
4,C1004,Mohit Arora,male,26.0,Gujarat,Ahmedabad,6.0,Premium,314.02,1926.12,One Year,Debit Card,Cable,Yes,No,No,No,02-04-2026
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
537,C5005,Sneha Jain,Female,115.0,Gujarat,Surat,1.0,NaN,1633.64,1707.64,Two Year,Debit Card,Cable,No,No,Yes,No,13-03-2026
538,C5006,Neha Verma,Female,18.0,Delhi,Noida,70.0,Standard,2008.83,140376.10,Month-to-Month,UPI,DSL,Yes,No,No,No,26-12-2025
539,C5007,Vikas Yadav,Male,61.0,Delhi,NaN,57.0,Basic,2196.18,125145.26,One Year,Cash,Cable,Yes,Yes,Yes,No,14-01-2025
540,C5008,Mohit Arora,Male,45.0,Gujarat,Ahmedabad,63.0,BASIC,1200.00,75799.15,Two Year,NaN,Fiber,Yes,No,No,No,28-02-2025
541,C5009,Rahul Singh,Male,25.0,UP,Kanpur,30.0,Basic,1341.52,NaN,Month-to-Month,Credit Card,Cable,No,No,Yes,No,29-11-2025

### Remove extra spaces

In [21]:
df=df.apply(lambda x:x.str.strip() if x.dtype=="object" else x)
df

,Customer_ID,Customer_Name,Gender,Age,State,City,Tenure_Months,Subscription_Type,Monthly_Charges,Total_Charges,Contract_Type,Payment_Method,Internet_Service,Tech_Support,Senior_Citizen,Dependents,Churn,Last_Interaction_Date
0,C1000,Abhishek Jaiswal,Female,35.0,Maharashtra,Pune,58.0,basic,1614.26,93273.08,One Year,UPI,Fiber,Yes,No,Yes,No,12-10-2025
1,C1001,Rohit Kumar,Male,NaN,Delhi,Noida,36.0,Premium,429.60,15858.60,Two Year,Cash,DSL,Yes,Yes,No,No,05-03-2026
2,C1002,Pooja Singh,Female,42.0,UP,Kanpur,13.0,Basic,555.03,6869.39,Month-to-Month,Debit Card,5G,No,No,No,Yes,20-02-2026
3,C1003,NaN,Male,59.0,Karnataka,Bengaluru,55.0,Standard,NaN,101349.10,Two Year,UPI,5G,No,No,Yes,No,07-06-2026
4,C1004,Mohit Arora,male,26.0,Gujarat,Ahmedabad,6.0,Premium,314.02,1926.12,One Year,Debit Card,Cable,Yes,No,No,No,02-04-2026
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
537,C5005,Sneha Jain,Female,115.0,Gujarat,Surat,1.0,NaN,1633.64,1707.64,Two Year,Debit Card,Cable,No,No,Yes,No,13-03-2026
538,C5006,Neha Verma,Female,18.0,Delhi,Noida,70.0,Standard,2008.83,140376.10,Month-to-Month,UPI,DSL,Yes,No,No,No,26-12-2025
539,C5007,Vikas Yadav,Male,61.0,Delhi,NaN,57.0,Basic,2196.18,125145.26,One Year,Cash,Cable,Yes,Yes,Yes,No,14-01-2025
540,C5008,Mohit Arora,Male,45.0,Gujarat,Ahmedabad,63.0,BASIC,1200.00,75799.15,Two Year,NaN,Fiber,Yes,No,No,No,28-02-2025
541,C5009,Rahul Singh,Male,25.0,UP,Kanpur,30.0,Basic,1341.52,NaN,Month-to-Month,Credit Card,Cable,No,No,Yes,No,29-11-2025

### Proper case

In [22]:
df["Customer_Name"]=df["Customer_Name"].str.title()
df["State"]=df["State"].str.title()
df["City"]=df["City"].str.title()
df["Subscription_Type"]=df["Subscription_Type"].str.title()
df["Contract_Type"]=df["Contract_Type"].str.title()
df

,Customer_ID,Customer_Name,Gender,Age,State,City,Tenure_Months,Subscription_Type,Monthly_Charges,Total_Charges,Contract_Type,Payment_Method,Internet_Service,Tech_Support,Senior_Citizen,Dependents,Churn,Last_Interaction_Date
0,C1000,Abhishek Jaiswal,Female,35.0,Maharashtra,Pune,58.0,Basic,1614.26,93273.08,One Year,UPI,Fiber,Yes,No,Yes,No,12-10-2025
1,C1001,Rohit Kumar,Male,NaN,Delhi,Noida,36.0,Premium,429.60,15858.60,Two Year,Cash,DSL,Yes,Yes,No,No,05-03-2026
2,C1002,Pooja Singh,Female,42.0,Up,Kanpur,13.0,Basic,555.03,6869.39,Month-To-Month,Debit Card,5G,No,No,No,Yes,20-02-2026
3,C1003,NaN,Male,59.0,Karnataka,Bengaluru,55.0,Standard,NaN,101349.10,Two Year,UPI,5G,No,No,Yes,No,07-06-2026
4,C1004,Mohit Arora,male,26.0,Gujarat,Ahmedabad,6.0,Premium,314.02,1926.12,One Year,Debit Card,Cable,Yes,No,No,No,02-04-2026
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
537,C5005,Sneha Jain,Female,115.0,Gujarat,Surat,1.0,NaN,1633.64,1707.64,Two Year,Debit Card,Cable,No,No,Yes,No,13-03-2026
538,C5006,Neha Verma,Female,18.0,Delhi,Noida,70.0,Standard,2008.83,140376.10,Month-To-Month,UPI,DSL,Yes,No,No,No,26-12-2025
539,C5007,Vikas Yadav,Male,61.0,Delhi,NaN,57.0,Basic,2196.18,125145.26,One Year,Cash,Cable,Yes,Yes,Yes,No,14-01-2025
540,C5008,Mohit Arora,Male,45.0,Gujarat,Ahmedabad,63.0,Basic,1200.00,75799.15,Two Year,NaN,Fiber,Yes,No,No,No,28-02-2025
541,C5009,Rahul Singh,Male,25.0,Up,Kanpur,30.0,Basic,1341.52,NaN,Month-To-Month,Credit Card,Cable,No,No,Yes,No,29-11-2025

### Standardize Churn Column

In [23]:
df["Churn"].value_counts()

Churn
No     405
Yes    125
YES      1
yes      1
Name: count, dtype: int64

In [24]:
df["Churn"]=df["Churn"].str.strip().str.upper()
df["Churn"]=df["Churn"].replace({
    "YES":"Yes",
    "NO":"No"
})
df["Churn"].value_counts()

Churn
No     405
Yes    127
Name: count, dtype: int64

### Convert Numeric Cols

In [25]:
cols=[
"Age",
"Tenure_Months",
"Monthly_Charges",
"Total_Charges"
]

for c in cols:
    df[c]=pd.to_numeric(df[c],errors="coerce")

### Remove Invalid Age

In [26]:
df=df[(df["Age"]>=18)&(df["Age"]<=100)]

### Remove Negative Charges

In [27]:
df=df[df["Monthly_Charges"]>=0]

df=df[df["Total_Charges"]>=0]

### Convert Date

In [28]:
df["Last_Interaction_Date"]=pd.to_datetime(
    df["Last_Interaction_Date"],
    errors="coerce"
)

### Fill Missing Values

In [29]:
df["Tech_Support"]=df["Tech_Support"].fillna("No")

df["Payment_Method"]=df["Payment_Method"].fillna("Unknown")

df["Monthly_Charges"]=df["Monthly_Charges"].fillna(df['Monthly_Charges'].mean())

df["Tenure_Months"]=df["Tenure_Months"].fillna(df['Tenure_Months'].mean())

df['Age'] = df['Age'].fillna(df['Age'].mean())

## Feature Engineering

In [30]:
df["Customer_Value"]=df["Monthly_Charges"]*df["Tenure_Months"]
print(f"Customer Lifetime Value (CLV): {round(df['Customer_Value'].sum(), 2)}")

Customer Lifetime Value (CLV): 24713881.88

In [31]:
df["Monthly_Revenue"]=df["Monthly_Charges"]
print(f"Total Monthly Revenue: {round(df['Monthly_Revenue'].sum(), 2)}")

Total Monthly Revenue: 668737.24

In [32]:
df["Tenure_Group"]=pd.cut(
df["Tenure_Months"],
bins=[0,12,24,48,72],
labels=["0-12","13-24","25-48","49-72"]
)
print(df["Tenure_Group"].value_counts())

Tenure_Group
25-48    183
49-72    144
13-24     88
0-12      77
Name: count, dtype: int64

In [33]:
df["Senior_Flag"]=np.where(df["Age"]>=60,"Senior","Adult")
print(df["Senior_Flag"].value_counts())

Senior_Flag
Adult     399
Senior     93
Name: count, dtype: int64

In [34]:
df["Churn_Flag"]=df["Churn"].map({
"Yes":1,
"No":0
})
print(df["Churn_Flag"].value_counts())

Churn_Flag
0.0    374
1.0    116
Name: count, dtype: int64

In [35]:
df.info()

<class 'pandas.DataFrame'>
Index: 492 entries, 0 to 540
Data columns (total 23 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Customer_ID            492 non-null    str
 1   Customer_Name          487 non-null    str
 2   Gender                 488 non-null    str
 3   Age                    492 non-null    float64
 4   State                  485 non-null    str
 5   City                   487 non-null    str
 6   Tenure_Months          492 non-null    float64
 7   Subscription_Type      486 non-null    str
 8   Monthly_Charges        492 non-null    float64
 9   Total_Charges          492 non-null    float64
 10  Contract_Type          490 non-null    str
 11  Payment_Method         492 non-null    str
 12  Internet_Service       486 non-null    str
 13  Tech_Support           492 non-null    str
 14  Senior_Citizen         486 non-null    str
 15  Dependents             491 non-null    str
 16  Churn                  490 non-null    str
 17  Last_Interaction_Date  178 non-null    datetime64[us]
 18  Customer_Value         492 non-null    float64
 19  Monthly_Revenue        492 non-null    float64
 20  Tenure_Group           492 non-null    category
 21  Senior_Flag            492 non-null    str
 22  Churn_Flag             490 non-null    float64
dtypes: category(1), datetime64[us](1), float64(7), str(14)
memory usage: 126.3 KB

In [36]:
df.describe()

,Age,Tenure_Months,Monthly_Charges,Total_Charges,Last_Interaction_Date,Customer_Value,Monthly_Revenue,Churn_Flag
count,492.000000,492.000000,492.000000,492.000000,178,492.000000,492.000000,490.000000
mean,43.191057,36.059548,1359.222033,50363.987561,2025-09-27 16:26:57.977528,50231.467233,1359.222033,0.236735
min,18.000000,1.000000,302.540000,354.120000,2025-01-01 00:00:00,379.700000,302.540000,0.000000
25%,30.000000,19.000000,762.940000,19129.100000,2025-04-06 00:00:00,19125.137500,762.940000,0.000000
50%,43.000000,37.000000,1308.510000,40668.695000,2025-08-24 00:00:00,40701.195000,1308.510000,0.000000
75%,56.000000,53.000000,1889.437500,74393.410000,2026-02-04 00:00:00,74097.160000,1889.437500,0.000000
max,70.000000,72.000000,2492.510000,171429.830000,2026-12-06 00:00:00,171658.830000,2492.510000,1.000000
std,15.401619,20.360662,653.133221,39760.135287,NaN,39647.442978,653.133221,0.425513

In [37]:
df.isnull().sum()

Customer_ID                0
Customer_Name              5
Gender                     4
Age                        0
State                      7
City                       5
Tenure_Months              0
Subscription_Type          6
Monthly_Charges            0
Total_Charges              0
Contract_Type              2
Payment_Method             0
Internet_Service           6
Tech_Support               0
Senior_Citizen             6
Dependents                 1
Churn                      2
Last_Interaction_Date    314
Customer_Value             0
Monthly_Revenue            0
Tenure_Group               0
Senior_Flag                0
Churn_Flag                 2
dtype: int64

In [38]:
df.to_excel(
    "C:/Users/LENOVO/Desktop/data-analytics/Customer Churn/dataset/Clean_Churn_Data.xlsx",
    index=False
)
print(f"Clean dataset saved Successfully!")

Clean dataset saved Successfully!